### PR TITLE
Settings and Credits

### PR DESCRIPTION
**Pull request by PBWiseman**
## Describe your changes

This branch will add the settings and credits pages to the main menu
List of things to do when merging:
The WaveMusic game object needs to be deleted from the main scene when merging
The CameraLoading script needs to be added to SkillMenu and MainScene
The Camera in MainScene needs to be set to main camera in the CameraLoading options and it needs to be set to 10 zoom
The background colour of Skill Menu needs to be changed to 80,80,80
OnArcadeLook needs to be added to movement on the player
OnLook needs to be added to look of player
Apply overrides to player prefab from main scene

## Issue number and link

#89 #90 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by PBWiseman** [comment]
Credits and settings are ready for review.

**Review by AlexReidNZ — CHANGES_REQUESTED** [review]
The settings menu looks and functions great, sound settings work as intended. Aiming seems to have somehow completely broken on this branch, at least for me.

**Comment by AlexReidNZ** [comment]
Screenshot 2024-09-17 153406
Adding colons here could help with clarity, especially for arcade display, where there is a smaller gap between "shooting" and "bottom left button" as it is quite long.

**Comment by PBWiseman** [comment]
Colons added. Aiming has been fixed when playing directly from the PalinScene scene and I can fix it in the main scene after merge. I had to change the aiming code, so I also added basic controller and arcade support. The gameplay itself works but the menus and the item selection are currently not navigable so those will need to be adjusted. Note that I have only tested the arcade and controller modes on a controller not on the actual arcade machine yet as the menus can't be navigated on it.

**Review by AlexReidNZ — APPROVED** [review]
Requested fixes have been made, this is ready for merging.

**Review by kblack89 — APPROVED** [review]
The code is well explained and from playtesting it works without any apparent bugs or issues.

**Review by Loerad — APPROVED** [review]
New sounds and settings look good as a start

**Pull request merged**
