### PR TITLE
Menu updates

### PR DESCRIPTION
**Pull request by PBWiseman**
## Describe your changes

This branch is implementing both the keyboard navigation of menus and standardizing the design.

Menus are fully navigable with keyboard or with controller.
Game is fully playable from start to finish with controller. You cannot enter a custom name, but it will enter the name "Player" for you.
Toggle shoot option added
Menu buttons and styles standardized across all scenes.

Bug fixes:
- Can no longer un-pause game while still in the settings menu

Bugs:
- Can't enter name on controller

## Issue number and link

#128 #127 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by kblack89 — APPROVED** [review]
The changes to being able to navigate the menus and settings are good, The code makes sense and the toggle shoot is helpful for the controller version of the game.

**Review by AlexReidNZ — APPROVED** [review]
Toggle shoot works well, menu navigation with controller is good, although can only be done with left stick, not with d-pad. If easy this should probably be done, but if not stick only is a fine enough first iteration. Happy to merge this.

**Comment by PBWiseman** [comment]
> Toggle shoot works well, menu navigation with controller is good, although can only be done with left stick, not with d-pad. If easy this should probably be done, but if not stick only is a fine enough first iteration. Happy to merge this.

Ran into issues trying to add d-pad navigation. Will shelve this for later

**Review by Loerad — CHANGES_REQUESTED** [review]
Change base branch

**Review by Loerad — APPROVED** [review]

**Pull request merged**
