### PR TITLE
Game audio refactor

### PR DESCRIPTION
**Pull request by kblack89**
Changing audio so we can adjust the volumes for all separate sounds and music. Also deleted unused directory.

### CODE REVIEW

**Review by AlexReidNZ — CHANGES_REQUESTED** [review]
When starting the game from the main scene in the editor, the volume balancing is good, but the game over sound plays at the start. When starting from the main menu, it still uses the old unbalanced sound where the player shot is very loud.

**Comment by AlexReidNZ** [comment]
> When starting the game from the main scene in the editor, the volume balancing is good, but the game over sound plays at the start. When starting from the main menu, it still uses the old unbalanced sound where the player shot is very loud.

This is happening because the SFXManager isn't destroyed on load and the new audio mixer hasn't been assigned on the main menu scene.

**Comment by kblack89** [comment]
After merge will change the game over sound to happen when there is a game state for game over rather than player health being at 0

**Review by AlexReidNZ — APPROVED** [review]
Requested change has been made, this branch is ready for merge.

**Review by PBWiseman — APPROVED** [review]
Working well. Happy for this to be merged

**Review by Loerad — APPROVED** [review]
Audio does not clip, good job

**Pull request merged**
