### PR TITLE
Final Boss

### PR DESCRIPTION
**Pull request by kblack89**
## Describe your changes
This should add a boss that:
-Spawns enemies at every 25% health loss
-Is invulnerable to damage until all enemies are defeated

## Issue number and link

#129

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by kblack89** [comment]
This has been tested and bleed etc stops effecting boss in its invulnerable state, explosions will be fixed once added from Palins other branch.

**Comment by kblack89** [comment]
Also ready for review

**Review by PBWiseman — DISMISSED** [review]

**Review by PBWiseman — COMMENTED** [review]
The functionality of the health gate and add spawning is good! There definitely needs to be some kind of visuals for the shield. Ideally both on the boss and the health bar. Not sure what other mechanics it could have though.

**Review by AlexReidNZ — COMMENTED** [review]
I agree that a visual is needed for the invulnerability, this could temporarily be just a colour/transparency change, with a proper visual added next sprint when adding the sprite for this boss. Health gates and enemy spawning work well. Definitely needs at least one other mechanic to be final boss worthy, although there may not be time to add it this sprint as we should probably discuss as a team and I doubt we could get it implemented by tomorrow afternoon.

**Comment by kblack89** [comment]
This is ready for review, please let me know how you find the boss difficulty and anything that I need to tweak.

**Comment by kblack89** [comment]
This is ready for review

**Review by AlexReidNZ — APPROVED** [review]
The final boss mechanics are fun and balanced, happy to merge this. Sprites for this boss can be implemented on staging.

**Comment by AlexReidNZ** [comment]
> The final boss mechanics are fun and balanced, happy to merge this. Sprites for this boss can be implemented on staging.

Actually, I will do this on this branch before merging once it is updated with the changes from last week.

**Review by PBWiseman — APPROVED** [review]
Use cases tested. All approved

**Review by Loerad — APPROVED** [review]
Final boos looks good

**Pull request merged**
