### PR TITLE
UI Changes

### PR DESCRIPTION
**Pull request by PBWiseman**
## Describe your changes

Implemented:
- Bandage icon for skip icon
- Shield icon for Peacekeeper
- Respawn UI
- Timer moved to middle of the screen

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by PBWiseman** [comment]
NOTE: To test please user no_egg_MainScene as the nest and eggs have been deleted

**Review by Loerad — CHANGES_REQUESTED** [review]
Love the new UI. The respawns text is way too big, I think changing the wording to be lives and making it a bit smaller could help

**Review by AlexReidNZ — APPROVED** [review]
New UI elements look great, I agree with Rohan's comment that the respawns text is too big but other than that really happy with this.

**Review by kblack89 — APPROVED** [review]
The UI changes look good, no apparent issues but this is more visual so not expected there to be.

**Review by Loerad — APPROVED** [review]

**Pull request merged**
