### PR TITLE
Boss Spawning

### PR DESCRIPTION
**Pull request by kblack89**
Adding Boss sprites, will be adding spawning etc to make this all work

### CODE REVIEW

**Comment by kblack89** [comment]
The timer now turns off at boss waves, the boss health bar disappears upon boss death and normal enemies don't  spawn durng boss waves.

**Comment by kblack89** [comment]
This is now ready for review

**Review by PBWiseman — CHANGES_REQUESTED** [review]
Looks really good! Boss spawns and level ends based on health. Only issue is that as far as I can tell the bossesSpawned list isn't being used and the boss spawned isn't unique. Once this is fixed it should be good to merge!

**Review by AlexReidNZ — CHANGES_REQUESTED** [review]
The boss spawning and boss health both work mostly as intended. I did find that if the boss dies to bleed it doesn't register and the game softlocks. I did figure out why, it's a simple fix that I can show you in person. The boss health is also way too low at 200, they die too easily. It should also probably increase with each boss.

**Review by Loerad — CHANGES_REQUESTED** [review]
Just need an answer on the wavechecker script then this is good to go.

**Review by AlexReidNZ — APPROVED** [review]
Bleed bug has been fixed, increased boss health feels a lot better. Ready for merge

**Review by PBWiseman — APPROVED** [review]

**Review by Loerad — APPROVED** [review]

**Pull request merged**
