### PR TITLE
Sword Upgrades

### PR DESCRIPTION
**Pull request by AlexReidNZ**
## Describe your changes

This branch will contain additional sword upgrades so that the sword can have a fully implemented upgrade tree.
It adds the following items:
* Reflector
* Claymore

## Issue number and link

#101 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by AlexReidNZ** [comment]
I would love some ideas for how the reflector item could be made stackable. Not sure exactly how this could be done.

**Comment by PBWiseman** [comment]
> I would love some ideas for how the reflector item could be made stackable. Not sure exactly how this could be done.

Possibly having the reflected bullet only do a % of the base damage and additional stacks increase the %? Another idea would be to have the reflection have a cooldown or only be every x number of swings and additional items decrease this

**Comment by Loerad** [comment]
I was also thinking some sort of cooldown that would be reduced with each stack

**Comment by AlexReidNZ** [comment]
Branch is ready for review now.

**Review by kblack89 — APPROVED** [review]
This looks good and makes sense. The cooldown for the reflector and other parts of this make sense and work fine in gameplay.

**Review by Loerad — APPROVED** [review]
All the new upgrades work great. Something to think about is if it only activates and starts the cooldown on a successful deflect.

**Pull request merged**
