### PR TITLE
06 kb blade boss

### PR DESCRIPTION
**Pull request by kblack89**
## Describe your changes

Adds in a boss that does charge attacks and has a ring of moving blades that hurt the player

#117

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by kblack89** [comment]
This is ready for review.

**Review by PBWiseman — CHANGES_REQUESTED** [review]
I like the boss. The blades are cool, and I like that they respawn around the player if they leave the zone.

The blades don't move when the game is paused but they do swap between moving in and out. You will need to either move it out of the coroutine to update or have the coroutine pause when the game is paused.
The decoy deletes blades when it collides with them.
The charge needs some sort of indicator that it's about to go off so it's easier to dodge.

Other than that, the boss seems good. Well done!

**Review by AlexReidNZ — APPROVED** [review]
This boss is really fun to fight and is a good level of challenge. I didn't spot any functionality issues besides those already pointed out by Palin. Great work.

**Review by AlexReidNZ — APPROVED** [review]
New changes look good, happy to merge this.

**Review by PBWiseman — APPROVED** [review]

**Pull request merged**
