### PR TITLE
Giving rocket launcher lifesteal

### PR DESCRIPTION
**Pull request by PBWiseman**
## Describe your changes

Fixes bug where rocket launcher couldn't lifesteal

## Issue number and link

#99 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by AlexReidNZ** [comment]
The lifesteal items should probably have their descriptions updated to reflect that they don't work with explosive/bleed/etc. Maybe something like "1% bullet lifesteal"

**Review by Loerad — APPROVED** [review]
Code change looks good

**Review by AlexReidNZ — APPROVED** [review]
Change works as intended, ready to merge.

**Review by kblack89 — APPROVED** [review]
This works after testing and is simple code so nothing else to add

**Pull request merged**
