### PR TITLE
v0.12.0

### PR DESCRIPTION
**Pull request by PBWiseman**
Changelog
-
- ADD: Credits page
- ADD: Settings page
    - Volume sliders
    - Resolution changing
    - Keybinding display
- ADD: Skills
    - Dash
    - Vanish
    - Decoy
- ADD: Shotgun boss
- ADD: Sword
- ADD: New upgrades
    - Radiating Bombs
    - MOAB
    - Sword of the Master

Bug fixes
-
- 16:10 menu scaling fixed
- Build name correct
- Can no longer speed click through item selection

Known bugs
- 
- Menus don't work on controller

Background Improvements
-
- Initial work for controller support

### CODE REVIEW

**Comment by PBWiseman** [comment]
Good to merge

**Review by AlexReidNZ — APPROVED** [review]
yes

**Review by Loerad — APPROVED** [review]
Yippee!!

**Review by kblack89 — APPROVED** [review]
I approve of the changes

**Pull request merged**
