### PR TITLE
Sprite Overhaul

### PR DESCRIPTION
**Pull request by AlexReidNZ**
## Describe your changes

This branch will contain all of the new sprites for the game. This will also contain a rework of map tiles, so that they can affect different entities in different ways.

## Issue number and link

#113 
#114

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by AlexReidNZ** [comment]
Ready for review now. A couple of things:
* The new tiles are in a dummy scene named NewTileTest as it would require edits to main scene.
* The old tiles are still in the files so main scene doesn't break, can be deleted after staging changes.
* I was going to clean up the file structure for the sprites, but moving around the old sprites was causing a few problems, so this has turned into a bigger issue that can be done next sprint during polishing.

**Review by PBWiseman — CHANGES_REQUESTED** [review]
New sprites look amazing! 

Bugs:
- If you kill a dog while it is biting you the bite animation becomes large and moves beside the tomb

- I love the bosses being so big and scary but the tombstone they leave behind should probably be a bit bigger as well

- The arrow pointing at the boss has disappeared

- Weapon isn't stealthed when player is. Likely not worth changing if this isn't easy?

- The first swing after you get the sword is always blue. I believe this is because all sprites under the sword start active rather than inactive. This seemed to fix it for me.

- Not a bug but is there any way you could quickly do a sword version that has reflector ready? Maybe a blue tinted one?

Couple of things that are either not from this branch or out of scope, but I noticed during testing and am making a note of:

- Explosions for weapons with quick bullet speed can appear noticeably behind enemies that are directly in front of you. This isn't a huge issue, partly because the player doesn't generally have enemies quite that close to them, but it should still be fixed at some point.

- The claymore looks a bit odd with the current animation just sitting there for ages. Definitely out of scope for this sprite overhaul but if there is another batch of sprites added at some point that should likely be included.

The sprites look amazing overall. They definitely improve the game. Great work!

**Comment by AlexReidNZ** [comment]
> * If you kill a dog while it is biting you the bite animation becomes large and moves beside the tomb

Fixed.

> * I love the bosses being so big and scary but the tombstone they leave behind should probably be a bit bigger as well

Fixed, did this by adding an IsBoss bool to enemy base which will also fix enemies spawned by final boss having the longer death timeout.

> * The arrow pointing at the boss has disappeared

No idea how that happened, will have to sort it out with Kyle tomorrow because I have no idea how that happened or how it works. Might need fixed on staging?

> * Weapon isn't stealthed when player is. Likely not worth changing if this isn't easy?

fixed.

> * The first swing after you get the sword is always blue. I believe this is because all sprites under the sword start active rather than inactive. This seemed to fix it for me.

Fixed.

**Review by PBWiseman — CHANGES_REQUESTED** [review]
Deleting the child prefabs means it can trigger a null reference exception on line 67 of EnemyMelee when it tries to set the attack to be not active. Just need that to have a not null check.

**Review by PBWiseman — APPROVED** [review]

**Review by Loerad — APPROVED** [review]
Love the new sprites, a needed refresh

**Pull request merged**
