### PR TITLE
New spawning system and enemy levels

### PR DESCRIPTION
**Pull request by AlexReidNZ**
## Describe your changes

This branch will contain the new spawning system, spawning enemies around the player rather than from set locations. It will also have new harder enemy variations that can be used instead of scaling enemy stats.

## Issue number and link

#13
#63 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by AlexReidNZ** [comment]
This branch is ready for review, bosses do 0 damage in this branch but I don't think it needs to be fixed here as bosses are being changed elsewhere and will need fixing up after merging anyway.

**Review by kblack89 — APPROVED** [review]
This is a good spawning overhaul and works well after testing. The enemies are now spawned better and the game is more fun because of the new enemies. No coding errors and looks good.

**Review by Loerad — APPROVED** [review]
Looks good, pulled into my branch and have experienced what it does.

**Review by PBWiseman — APPROVED** [review]
No issues found. Happy for this to be merged

**Pull request merged**
