### PR TITLE
Skill related items and Death's Dance

### PR DESCRIPTION
**Pull request by Loerad**
## Describe your changes

I have added the skill items we discussed. The numbers might be a little bit too overtuned but we can playtest that.

**Note:** I have change how items are handled in the backend to be able to have single pickups. It now throws the whole item over instead of just the ID in the item effect table. This shouldn't break anything but new ways to add items will have to account for this.

I have added:
```
     {
        "id": 37,
        "name": "Second Wind",
        "desc": "Decrease your skill cooldown by 10%",
        "rarity": 1,
        "stacks": 0
      },
      {
        "id": 38,
        "name": "Increased Focus",
        "desc": "Increase your skill duration by 10%",
        "rarity": 1,
        "stacks": 0
      },
      {
        "id": 39,
        "name": "Cursed Dash",
        "desc": "Dash cooldown is reduced by 50%, but you no longer gain immunity during dash",
        "rarity": 6,
        "skills": ["dash"],
        "single": false,
        "stacks": 0
      },
      {
        "id": 40,
        "name": "Corrupted Vanish",
        "desc": "Your shots during vanish deal 300% damage, but vanish cooldown is increased by 100% and duration is reduced by 50%",
        "rarity": 6,
        "skills": ["vanish"],
        "single": false,
        "stacks": 0
      },
      {
        "id": 41,
        "name": "Corrupted Decoy",
        "desc": "Decoy explodes at the end of its duration for 100 times player damage, but decoy cooldown is increased by 25%",
        "rarity": 6,
        "skills": ["decoy"],
        "single": false,
        "stacks": 0
      },
      {
        "id": 42,
        "name": "Corrupted Dance",
        "desc": "Your Crit and Crit Damage scale based on missing health, up to 80%",
        "rarity": 6,
        "single": false,
        "stacks": 0
      }
```
## Issue number and link

#118 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Loerad** [comment]
I forgot to mention, the decoy explosion will error, you need to add the explosion prefab to the skilleffects script on the player.

**Review by PBWiseman — APPROVED** [review]
Love the new items. They all seem cool. Balance will need testing, but my first guess is that deaths dance and cursed dash are about right, cursed decoy and cursed vanish might be weak but with the right build probably very good. The cooldown item should probably be:
```
SkillEffects.Instance.cooldownModifier *= 0.9f;
```
This way it doesn't remove 10% of the original value but 10% of the modified one and we don't get an attack speed problem with things scaling insanely fast. This is what I changed the attack speed scaling in my #125 branch to

**Review by kblack89 — APPROVED** [review]
The new items are fun , will need to do some more playtesting, from what I did I found them fun and no apparent issues

**Review by AlexReidNZ — APPROVED** [review]
New items work well, corrupted skills are cool. didn't notice any bugs, ready to merge.

**Pull request merged**
