### PR TITLE
General bugfixes

### PR DESCRIPTION
**Pull request by PBWiseman**
## Describe your changes

Fixing a long list of misc bugs. Some will be done this sprint. Some carried over into the polishing sprint.
One report of lucky dip selecting the same stat twice. Code should never be able to do this. Cannot replicate bug.

Bugs that need to be fixed
- Sword goes through Peacekeeper shield. Doesn't damage it and only hits health bar

Bug fixes
-
- Dash tooltip change (Visual change only. No mechanical changes)
- Crit chance display capped at 100% (Visual change only)
- Movement speed display decimal places capped (Visual change only)
- Player can no longer appear to lifesteal after death (Visual change only)
- Endless mode no longer ends at wave 25
- Napalm bombs now target decoy
- Napalm now despawns on boss death
- Fixed camera jittering with higher movement speed
- Enemies spawn properly during Vanish
- Jumping-Jack now updates target selection mid jump when a decoy is placed or de-spawns
- Attack speed now scales at a consistent rate

Behind the scenes (not in patch notes):
- Terminal line break now correct length
- Culling boss wave no longer breaks game

### CODE REVIEW

**Comment by PBWiseman** [comment]
NOTE: The fix to camera jittering is in the CameraFix branch. The best way to test it is to give yourself a large amount of movement speed. The movement looks a lot smoother. To merge this into main scene in staging we will need to move main camera into the player prefab and remove the CameraFollow script (we can delete this script as well).

**Comment by PBWiseman** [comment]
All fixes except for sword related ones have been implemented. The sword ones will wait until the new sword swing.

**Review by AlexReidNZ — CHANGES_REQUESTED** [review]
Did a full boss mode playthrough of this branch, didn't encounter any of the listed bugs.
I did however encounter a new bug with the stats display on item pickup: after taking spine plate, my move speed showed red after every item picked. It wasn't changing the number or the actual speed, just showing as if every item reduced speed.

Another issue encountered with the stat display, when taking excess crit the crit chance shows over 100%. This isn't needed, as the excess crit -> crit damage conversion is displayed in the crit damage number.

**Comment by PBWiseman** [comment]
> Did a full boss mode playthrough of this branch, didn't encounter any of the listed bugs. I did however encounter a new bug with the stats display on item pickup: after taking spine plate, my move speed showed red after every item picked. It wasn't changing the number or the actual speed, just showing as if every item reduced speed.

Could not reproduce bug with either terminal giving the item or skipping to wave 15 and picking it. Can you think of anything else that could have influenced the bug that I can test?

> Another issue encountered with the stat display, when taking excess crit the crit chance shows over 100%. This isn't needed, as the excess crit -> crit damage conversion is displayed in the crit damage number.

Fixed.

**Review by kblack89 — APPROVED** [review]
I didn't find any of the bugs that this branch fixed so well done. The code made sense and was commented well in areas that needed a bit more explaining.

**Review by AlexReidNZ — APPROVED** [review]
Requested changes made. Good to merge.

**Review by Loerad — APPROVED** [review]
Looks good!

**Pull request merged**
