### PR TITLE
Sword functionality and new items

### PR DESCRIPTION
**Pull request by AlexReidNZ**
## Describe your changes

This pull request will contain a rework for the functionality of the sword weapon, as well as the following items:
* Radiating Bombs (rocket upgrade)
* MOAB (rocket upgrade)
* Sword of the Master (sword upgrade)

## Issue number and link

#82 
#84 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by AlexReidNZ** [comment]
Ready for review, would specifically like some feedback on the sword functionality.
Note: The sword doesn't effect bosses in this branch. This is because the sword damages based on the EnemyBase script, which is being added to the bosses on another branch this sprint. It should work after merging but I'll merge that branch into here to test once it's finished as well.

**Review by PBWiseman — CHANGES_REQUESTED** [review]
Happy with the implementation of the sword and rocket launcher. The only breaking change is that there needs to be 2 more temporary epic items for the sword in order to not break the epic reward screen.

More minor: all other rewards give stacking benefit. Thoughts on the sword beam damage increasing in order to give that stacking benefit as well?

Finally I was testing the sword against the bomb boss and it seems much too hard. We can discuss this in the meeting but we should consider making the bombs not explode when you touch them, only at the end of the fuse. That would make it a lot less frustrating to be melee against them

**Comment by AlexReidNZ** [comment]
> Happy with the implementation of the sword and rocket launcher. The only breaking change is that there needs to be 2 more temporary epic items for the sword in order to not break the epic reward screen.

There are 2 temp sword items, do they not appear properly?

> More minor: all other rewards give stacking benefit. Thoughts on the sword beam damage increasing in order to give that stacking benefit as well?

Added a small stacking damage increase on multiple stacks.

**Comment by PBWiseman** [comment]
> There are 2 temp sword items, do they not appear properly?

I wasn't able to test it in game due to the boss being impossible to hit. I just didn't see them in the effect table, but I see them now in the Json. Should work fine

**Review by PBWiseman — APPROVED** [review]

**Review by Loerad — APPROVED** [review]
All changes look good, there is no outstanding bugs I found. I like the new items

**Review by kblack89 — APPROVED** [review]
After playtesting the new sword and rocket launcher changes work well and are fun. No bugs that are apparent and the code is clean and explained well

**Pull request merged**
